name: kazoo-configs-rabbitmq
base_branch: origin/4.3
base_core: null
template: spec.tmpl
package:
  centos7:
    name: kazoo-configs-rabbitmq
    group: Productivity/Telephony
    license: MPL1.1
    build_arch: noarch
    build_requires:
      - rpm-build
    summary: Kazoo specific configuration for RabbitMQ
    description: |
      The Kazoo platform uses RabbitMQ as the AMQP broker
      for all internal application messaging.  This package
      contains some configuration parameters for this service.
      If you need help you can contact us via the dev mailing
      list or on IRC at #2600hz on FreeNode.
    dist: .el7.centos
    requires:
      centos7:
         sudo: {}
    source: '%{_build_tar}'
    prep: '%setup -q'
    install: |
      mkdir -p %{buildroot}/etc/kazoo
      cp -r rabbitmq %{buildroot}/etc/kazoo
      cp CHANGELOG VERSION %{buildroot}/etc/kazoo/rabbitmq

      mkdir -p %{buildroot}/usr/sbin
      cp -r  system/sbin/* %{buildroot}/usr/sbin
      chmod +x %{buildroot}/usr/sbin/*

      mkdir -p %{buildroot}/etc/logrotate.d
      cp -r  system/logrotate.d/*.conf %{buildroot}/etc/logrotate.d

      mkdir -p %{buildroot}/etc/security/limits.d
      cp -r  system/security/limits.d/*.conf %{buildroot}/etc/security/limits.d

      mkdir -p %{buildroot}/usr/lib/systemd/system
      cp system/systemd/* %{buildroot}/usr/lib/systemd/system
    files:
      doc:
        - CHANGELOG
        - VERSION
      config:
        - mode: noreplace
          path: /etc/kazoo/rabbitmq
        - mode: noreplace
          path: /etc/logrotate.d/*rabbitmq*
        - mode: noreplace
          path: /etc/security/limits.d/*rabbitmq*
      path:
        - /usr/sbin/kazoo-rabbitmq
        - /usr/lib/systemd/system/kazoo-rabbitmq.service
    url: 'http://www.2600hz.org'
    vendor: 2600Hz
metapackage:
  -
    name: meta-kazoo-rabbitmq
    package: kazoo-configs-rabbitmq
    type: required
    branch: '4.3'
